In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 

In [2]:
df = pd.read_csv('/Users/vivektripathi/Desktop/machineLearning/Country Population Analysis.csv')
df.head(10)

Country ISO3  Year  Population  Population Growth  Growth Rate (%)  \
0  Afghanistan  AFG  1960     8996973                NaN              NaN   
1  Afghanistan  AFG  1961     9169410           172437.0         1.916611   
2  Afghanistan  AFG  1962     9351441           182031.0         1.985199   
3  Afghanistan  AFG  1963     9543205           191764.0         2.050636   
4  Afghanistan  AFG  1964     9744781           201576.0         2.112246   
5  Afghanistan  AFG  1965     9956320           211539.0         2.170793   
6  Afghanistan  AFG  1966    10174836           218516.0         2.194747   
7  Afghanistan  AFG  1967    10399926           225090.0         2.212222   
8  Afghanistan  AFG  1968    10637063           237137.0         2.280180   
9  Afghanistan  AFG  1969    10893776           256713.0         2.413382   

  Decade  
0  1960s  
1  1960s  
2  1960s  
3  1960s  
4  1960s  
5  1960s  
6  1960s  
7  1960s  
8  1960s  
9  1960s

In [3]:
df.tail()

Country ISO3  Year  Population  Population Growth  Growth Rate (%)  \
15404  Zimbabwe  ZWE  2014    13586681           236325.0         1.770178   
15405  Zimbabwe  ZWE  2015    13814629           227948.0         1.677731   
15406  Zimbabwe  ZWE  2016    14030390           215761.0         1.561830   
15407  Zimbabwe  ZWE  2017    14236745           206355.0         1.470772   
15408  Zimbabwe  ZWE  2018    14439018           202273.0         1.420781   

      Decade  
15404  2010s  
15405  2010s  
15406  2010s  
15407  2010s  
15408  2010s

In [4]:
#cleaning the dataset
df.isnull().sum()

Country                0
ISO3                   0
Year                   0
Population             0
Population Growth    263
Growth Rate (%)      263
Decade                 0
dtype: int64

In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')
imputed_df = imputer.fit_transform(df[['Growth Rate (%)','Population Growth']])

In [6]:
imputed_df

array([[1.81304841e+00, 3.29791186e+06],
       [1.91661129e+00, 1.72437000e+05],
       [1.98519861e+00, 1.82031000e+05],
       ...,
       [1.56182985e+00, 2.15761000e+05],
       [1.47077166e+00, 2.06355000e+05],
       [1.42078122e+00, 2.02273000e+05]], shape=(15409, 2))

In [7]:
imputed_df = pd.DataFrame(imputed_df,columns=['Growth Rate (%)','Population Growth'])
imputed_df.head()

Growth Rate (%)  Population Growth
0         1.813048       3.297912e+06
1         1.916611       1.724370e+05
2         1.985199       1.820310e+05
3         2.050636       1.917640e+05
4         2.112246       2.015760e+05

In [8]:
imputed_df.isnull().sum()

Growth Rate (%)      0
Population Growth    0
dtype: int64

In [9]:
df = df.drop(['Growth Rate (%)',"Population Growth"],axis=1)

In [10]:
df_1 = pd.concat([df,imputed_df],axis=1)
df_1.head(10)

Country ISO3  Year  Population Decade  Growth Rate (%)  \
0  Afghanistan  AFG  1960     8996973  1960s         1.813048   
1  Afghanistan  AFG  1961     9169410  1960s         1.916611   
2  Afghanistan  AFG  1962     9351441  1960s         1.985199   
3  Afghanistan  AFG  1963     9543205  1960s         2.050636   
4  Afghanistan  AFG  1964     9744781  1960s         2.112246   
5  Afghanistan  AFG  1965     9956320  1960s         2.170793   
6  Afghanistan  AFG  1966    10174836  1960s         2.194747   
7  Afghanistan  AFG  1967    10399926  1960s         2.212222   
8  Afghanistan  AFG  1968    10637063  1960s         2.280180   
9  Afghanistan  AFG  1969    10893776  1960s         2.413382   

   Population Growth  
0       3.297912e+06  
1       1.724370e+05  
2       1.820310e+05  
3       1.917640e+05  
4       2.015760e+05  
5       2.115390e+05  
6       2.185160e+05  
7       2.250900e+05  
8       2.371370e+05  
9       2.567130e+05

In [11]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse_output=False,handle_unknown='ignore')

df_1_encoded = ohe.fit_transform(df_1[['Country','ISO3']])

print(df_1_encoded)

df_1_encoded = pd.DataFrame(df_1_encoded,columns=ohe.get_feature_names_out(['Country','ISO3']))

final_data = pd.concat([df_1.drop(['Country','ISO3'],axis=1),df_1_encoded],axis=1)

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [12]:
final_data.head(10)

Year  Population Decade  Growth Rate (%)  Population Growth  \
0  1960     8996973  1960s         1.813048       3.297912e+06   
1  1961     9169410  1960s         1.916611       1.724370e+05   
2  1962     9351441  1960s         1.985199       1.820310e+05   
3  1963     9543205  1960s         2.050636       1.917640e+05   
4  1964     9744781  1960s         2.112246       2.015760e+05   
5  1965     9956320  1960s         2.170793       2.115390e+05   
6  1966    10174836  1960s         2.194747       2.185160e+05   
7  1967    10399926  1960s         2.212222       2.250900e+05   
8  1968    10637063  1960s         2.280180       2.371370e+05   
9  1969    10893776  1960s         2.413382       2.567130e+05   

   Country_Afghanistan  Country_Albania  Country_Algeria  \
0                  1.0              0.0              0.0   
1                  1.0              0.0              0.0   
2                  1.0              0.0              0.0   
3                  1.0              0.0              0.0   
4                  1.0              0.0              0.0   
5                  1.0              0.0              0.0   
6                  1.0              0.0              0.0   
7                  1.0              0.0              0.0   
8                  1.0              0.0              0.0   
9                  1.0              0.0              0.0   

   Country_American Samoa  Country_Andorra  ...  ISO3_VIR  ISO3_VNM  ISO3_VUT  \
0                     0.0              0.0  ...       0.0       0.0       0.0   
1                     0.0              0.0  ...       0.0       0.0       0.0   
2                     0.0              0.0  ...       0.0       0.0       0.0   
3                     0.0              0.0  ...       0.0       0.0       0.0   
4                     0.0              0.0  ...       0.0       0.0       0.0   
5                     0.0              0.0  ...       0.0       0.0       0.0   
6                     0.0              0.0  ...       0.0       0.0       0.0   
7                     0.0              0.0  ...       0.0       0.0       0.0   
8                     0.0              0.0  ...       0.0       0.0       0.0   
9                     0.0              0.0  ...       0.0       0.0       0.0   

   ISO3_WLD  ISO3_WSM  ISO3_XKX  ISO3_YEM  ISO3_ZAF  ISO3_ZMB  ISO3_ZWE  
0       0.0       0.0       0.0       0.0       0.0       0.0       0.0  
1       0.0       0.0       0.0       0.0       0.0       0.0       0.0  
2       0.0       0.0       0.0       0.0       0.0       0.0       0.0  
3       0.0       0.0       0.0       0.0       0.0       0.0       0.0  
4       0.0       0.0       0.0       0.0       0.0       0.0       0.0  
5       0.0       0.0       0.0       0.0       0.0       0.0       0.0  
6       0.0       0.0       0.0       0.0       0.0       0.0       0.0  
7       0.0       0.0       0.0       0.0       0.0       0.0       0.0  
8       0.0       0.0       0.0       0.0       0.0       0.0       0.0  
9       0.0       0.0       0.0       0.0       0.0       0.0       0.0  

[10 rows x 531 columns]

In [13]:
final_data.shape

(15409, 531)

In [14]:
#splitting of dataset 
X = final_data.copy()
y = X.pop('Population')

from sklearn.model_selection import train_test_split
X_train, X_valid, y_train, y_valid = train_test_split(X,y,test_size=0.2,random_state=42)

In [15]:
print(X.isnull().sum())

Year                   0
Decade                 0
Growth Rate (%)        0
Population Growth      0
Country_Afghanistan    0
                      ..
ISO3_XKX               0
ISO3_YEM               0
ISO3_ZAF               0
ISO3_ZMB               0
ISO3_ZWE               0
Length: 530, dtype: int64


In [16]:
print(X_train.shape,X_valid.shape)

(12327, 530) (3082, 530)


In [22]:
print(X_train.select_dtypes(include=['object']))
print(X_train.select_dtypes(exclude=['object']))

      Decade
1347   2000s
13146  1960s
316    1980s
15353  1960s
4269   1980s
...      ...
5191   1960s
13418  2000s
5390   1980s
860    1990s
7270   1980s

[12327 rows x 1 columns]
       Year  Growth Rate (%)  Population Growth  Country_Afghanistan  \
1347   2009         0.556126              363.0                  0.0   
13146  1968         5.548780              273.0                  0.0   
316    1981         3.586460           299157.0                  0.0   
15353  1963         3.454272           139525.0                  0.0   
4269   1988         0.334349          1028083.0                  0.0   
...     ...              ...                ...                  ...   
5191   1966         2.147816              560.0                  0.0   
13418  2004         2.677384         19267352.0                  0.0   
5390   1988        -1.323464            -1316.0                  0.0   
860    1994         1.762282             4777.0                  0.0   
7270   1980         1.3720

In [18]:
# for colname in X.select_dtypes(include='object'):
#     X[colname],_ = X[colname].factorize()

# discrete_features = X.dtypes == int

# X_categorical = X.select_dtypes(include='object').apply(lambda col:col.factorize()[0] )
# X_numerical = X.select_dtypes(exclude='object')

# X_final = pd.concat([X_categorical,X_numerical],axis=1)

In [20]:
from sklearn.preprocessing import StandardScaler 
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_valid_scaled = scaler.transform(X_valid)


ValueError: could not convert string to float: '2000s'