<a href="https://colab.research.google.com/github/Lawkage1/Data-Analysis-With-Python/blob/main/basic_pred_airquality.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Air Quality Pollution Assessment.zip to Air Quality Pollution Assessment.zip


In [ ]:
import zipfile, os

In [ ]:
with zipfile.ZipFile('Air Quality Pollution Assessment.zip','r') as zip_ref:
  zip_ref.extractall('Air Quality Pollution Assessment')

In [ ]:
extracted_file = os.listdir('Air Quality Pollution Assessment')
print(extracted_file)

['updated_pollution_dataset.csv']


In [ ]:
csv_file = 'Air Quality Pollution Assessment/updated_pollution_dataset.csv'
df = pd.read_csv(csv_file)

In [ ]:
df.head()

Temperature  Humidity  PM2.5  PM10   NO2   SO2    CO  \
0         29.8      59.1    5.2  17.9  18.9   9.2  1.72   
1         28.3      75.6    2.3  12.2  30.8   9.7  1.64   
2         23.1      74.7   26.7  33.8  24.4  12.6  1.63   
3         27.1      39.1    6.1   6.3  13.5   5.3  1.15   
4         26.5      70.7    6.9  16.0  21.9   5.6  1.01   

   Proximity_to_Industrial_Areas  Population_Density Air Quality  
0                            6.3                 319    Moderate  
1                            6.0                 611    Moderate  
2                            5.2                 619    Moderate  
3                           11.1                 551        Good  
4                           12.7                 303        Good

In [ ]:
df.tail()

Temperature  Humidity  PM2.5   PM10   NO2   SO2    CO  \
4995         40.6      74.1  116.0  126.7  45.5  25.7  2.11   
4996         28.1      96.9    6.9   25.0  25.3  10.8  1.54   
4997         25.9      78.2   14.2   22.1  34.8   7.8  1.63   
4998         25.3      44.4   21.4   29.0  23.7   5.7  0.89   
4999         24.1      77.9   81.7   94.3  23.2  10.5  1.38   

      Proximity_to_Industrial_Areas  Population_Density Air Quality  
4995                            2.8                 765   Hazardous  
4996                            5.7                 709    Moderate  
4997                            9.6                 379    Moderate  
4998                           11.6                 241        Good  
4999                            8.3                 461    Moderate

#**Data Cleaning**

In [ ]:
print(df.isnull().sum())

Temperature                      0
Humidity                         0
PM2.5                            0
PM10                             0
NO2                              0
SO2                              0
CO                               0
Proximity_to_Industrial_Areas    0
Population_Density               0
Air Quality                      0
dtype: int64


#**Train Test Split**

In [ ]:
X = df.drop(columns=['Air Quality'])
y = df['Air Quality']

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_valid,y_train,y_valid = train_test_split(X,y,test_size=0.2,random_state=0)

#**PreProcessing**

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_valid_scaled = scaler.transform(X_valid)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix,accuracy_score
model = RandomForestClassifier(random_state=42)
model.fit(X_train_scaled,y_train)
y_pred = model.predict(X_valid_scaled)
print(classification_report(y_valid, y_pred))
print(confusion_matrix(y_valid, y_pred))

              precision    recall  f1-score   support

        Good       1.00      1.00      1.00       411
   Hazardous       0.88      0.79      0.83       106
    Moderate       0.97      0.97      0.97       295
        Poor       0.85      0.88      0.86       188

    accuracy                           0.95      1000
   macro avg       0.92      0.91      0.92      1000
weighted avg       0.95      0.95      0.95      1000

[[411   0   0   0]
 [  0  84   0  22]
 [  0   0 287   8]
 [  0  12  10 166]]


In [ ]:
accuracy = accuracy_score(y_valid, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.948
