<a href="https://colab.research.google.com/github/Lawkage1/Data-Analysis-With-Python-/blob/main/CrazyNumpyStack.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#PREQUISITE FOR DEEP LEARNING

# **Numpy**

# Arrays vs List

In [ ]:
import numpy as np


In [ ]:
L = [1,2,3,4]
print(L)

[1, 2, 3, 4]


In [ ]:
A = np.array([1,2,3,4])
print(A)

[1 2 3 4]


In [ ]:
L+[5]


[1, 2, 3, 4, 5]

In [ ]:
A+np.array([5])

array([6, 7, 8, 9])

In [ ]:
A+np.array([5,6,7,8]) #you cant add vectors of different sizes i.e., 1 2 3 with 4 5

array([ 6,  8, 10, 12])

In [ ]:
2*A #scalar

array([2, 4, 6, 8])

In [ ]:
2*L

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
l2 = [e*e for e in L]
l2

[1, 4, 9, 16]

In [ ]:
A**2

array([ 1,  4,  9, 16])

In [ ]:
np.sqrt(A)


array([1.        , 1.41421356, 1.73205081, 2.        ])

In [ ]:
np.log(A)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [ ]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475, 0.9993293 ])

In [ ]:
x = np.array([90,60,0])
x

array([90, 60,  0])

In [ ]:
res = np.sin(x)
res

array([ 0.89399666, -0.30481062,  0.        ])

In [ ]:
radians = np.deg2rad(x)
res = np.sin(radians)
res

array([1.       , 0.8660254, 0.       ])

#Dot Product

In [ ]:
dot = 0
a = np.array([1,2,3])
b = np.array([4,5,6])
# res = [e*f for e,f in zip(a,b)]
# res
for e,f in zip(a,b):
  dot+=e*f



In [ ]:
dot

32

In [ ]:
dot = 0
for i in range(len(b)):
  dot+= a[i]*b[i]
dot

32

In [ ]:
a*b
np.sum(a*b)

32

In [ ]:
a.dot(b)

32

In [ ]:
np.dot(a,b)

32

In [ ]:
a@b

32

In [ ]:
a**2

array([1, 4, 9])

In [ ]:
amag = np.sqrt((a*a).sum())
amag

3.7416573867739413

In [ ]:
amag = np.linalg.norm(a)
amag

In [ ]:
amag2 = np.linalg.norm(b)
amag2

8.774964387392123

In [ ]:
cosangle = np.sum(a*b)/(np.linalg.norm(a)*np.linalg.norm(b))
cosangle

0.9746318461970762

In [ ]:
radians = np.deg2rad(cosangle)
radians

0.017010534710929955

#Speed Test

In [ ]:
from datetime import datetime
import numpy as np

a = np.random.randn(100)
b = np.random.randn(100)
T = 100000

def slow_dotprod(a, b):
    result = 0
    for e, f in zip(a, b):
        result += e * f
    return result

# Timing slow_dotprod
t0 = datetime.now()
for _ in range(T):
    slow_dotprod(a, b)
dt1 = datetime.now() - t0

# Timing np.dot
t0 = datetime.now()
for _ in range(T):
    a.dot(b)
dt2 = datetime.now() - t0

print("Slow dot product time:", dt1.total_seconds())
print("Numpy dot product time:", dt2.total_seconds())

# Ratio of slow to numpy dot product time
print("Ratio (slow/np.dot):", dt1.total_seconds() / dt2.total_seconds())


Slow dot product time: 5.999597
Numpy dot product time: 0.384044
Ratio (slow/np.dot): 15.62216048161148


#Matrices

In [ ]:
import numpy as np

In [ ]:
L = [[1,2],[3,4]]
L

[[1, 2], [3, 4]]

In [ ]:
L[0][1]

2

In [ ]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [ ]:
A[0][1]

2

In [ ]:
A[0,1]

2

In [ ]:
A[:,0]

array([1, 3])

In [ ]:
A[:,1]

array([2, 4])

In [ ]:
A.T


array([[1, 3],
       [2, 4]])

In [ ]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [ ]:
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [ ]:
B = np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [ ]:
np.linalg.det(A)

-2.0000000000000004

In [ ]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
np.linalg.inv(A).dot(A) #identity matrix

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [ ]:
np.trace(B)

6

In [ ]:
np.diag(B)

array([1, 5])

In [ ]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
np.linalg.eig(A)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [ ]:
EV, Vec = np.linalg.eig(A)

In [ ]:
EV

array([-0.37228132,  5.37228132])

In [ ]:
Vec

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

In [ ]:
Vec[:,0]*EV[0],A@Vec[:, 0]


(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

In [ ]:
Vec[:,0]*EV[0]==A@Vec[:, 0]

array([ True, False])

In [ ]:
np.allclose(Vec[:,0]*EV[0],A@Vec[:, 0])

True

In [ ]:
A = np.array([[1,1],[1.5,4]])
B = np.array([2200,5050])

In [ ]:
res = np.linalg.inv(A).dot(B)
res

array([1500.,  700.])

In [ ]:
np.linalg.solve(A,B) #doesnt solve singular matrix i.e., doesnt have an inverse

array([1500.,  700.])

#Generating Data

In [ ]:
import numpy as np

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
12*np.ones((2,2))

array([[12., 12.],
       [12., 12.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.randn(2)

array([-0.17551197, -0.81602064])

In [ ]:
np.random.randn(5,3)

array([[-0.51930932,  1.11656124,  2.20955806],
       [ 0.53518776, -0.93245833, -0.96750041],
       [ 0.7979701 , -0.55048407,  0.40769292],
       [ 0.40825868, -0.29157421, -0.24024602],
       [-0.85778289,  0.79140777,  1.3853405 ]])

In [ ]:
np.random.random((2,3))

array([[0.3456116 , 0.50467063, 0.86274572],
       [0.42361263, 0.58052624, 0.15792799]])

In [ ]:
R = np.random.randn(10000)

In [ ]:
R.mean()

-0.024457109662084905

In [ ]:
np.mean(R)

-0.024457109662084905

In [ ]:
np.var(R)

0.9690181884284313

In [ ]:
np.std(R)

0.9843872146815151

In [ ]:
R = np.random.randn(10000,3)

In [ ]:
R.mean(axis=0) #mean of the columns i.e., 3

array([ 0.00225099, -0.01235822,  0.01090384])

In [ ]:
R.mean(axis=1).shape

(10000,)

In [ ]:
np.cov(R)

array([[ 0.80496609, -0.10491309,  0.75285413, ..., -0.53650116,
        -0.12322314, -0.65136816],
       [-0.10491309,  0.89606157, -0.00105815, ...,  0.12194898,
         0.28030157,  0.32868511],
       [ 0.75285413, -0.00105815,  0.71479277, ..., -0.49604627,
        -0.08617922, -0.58238274],
       ...,
       [-0.53650116,  0.12194898, -0.49604627, ...,  0.36063962,
         0.09770656,  0.44850369],
       [-0.12322314,  0.28030157, -0.08617922, ...,  0.09770656,
         0.09799314,  0.17271664],
       [-0.65136816,  0.32868511, -0.58238274, ...,  0.44850369,
         0.17271664,  0.5944345 ]])

In [ ]:
np.cov(R.T)

array([[ 1.01234495,  0.00940358,  0.00618094],
       [ 0.00940358,  0.99359175, -0.00786719],
       [ 0.00618094, -0.00786719,  1.0205448 ]])

In [ ]:
np.cov(R,rowvar=False) #for columns to be vector observation otherwise rows are

array([[ 1.01234495,  0.00940358,  0.00618094],
       [ 0.00940358,  0.99359175, -0.00786719],
       [ 0.00618094, -0.00786719,  1.0205448 ]])

In [ ]:
np.random.randint(2,6,size=(2,2))

array([[3, 5],
       [3, 2]])

In [ ]:
np.random.randint(2,6,(3,3))

array([[3, 2, 5],
       [3, 5, 4],
       [5, 2, 2]])

In [ ]:
np.random.choice(8,(3,3))

array([[5, 6, 0],
       [3, 7, 7],
       [6, 7, 3]])

In [ ]:
np.random.choice(np.array([1,2,3,4,5]),size=(3,3),replace=True)

array([[1, 4, 4],
       [3, 5, 2],
       [4, 4, 3]])

In [ ]:
np.random.choice(12,(2,2),replace=False)

array([[4, 5],
       [2, 8]])

#Numpy Exercise

In [ ]:
import numpy as np
from datetime import datetime

T = 100000

a = [[1,2],[3,4]]
b = [[5,6],[7,8]]
res = [[0,0],[0,0]]
t0 = datetime.now()
for _ in range(T):
  for i in range(len(a)):
    for j in range(len(b[0])):
      for k in range(len(b)):
        res[i][j]+= a[i][k]*b[k][j]
dt1 = datetime.now()-t0

x = np.array(a)
y = np.array(b)

t0 = datetime.now()
for _ in range(T):
  x.dot(b)
dt2 = datetime.now()-t0

print("List matrix multiplication time:",dt1.total_seconds())
print("Numpy arrays multiplication time:",dt2.total_seconds())
print("total gap in btw:",dt1.total_seconds()/dt2.total_seconds())



List matrix multiplication time: 1.294425
Numpy arrays multiplication time: 0.267661
total gap in btw: 4.836061286478045
